# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0002_auto_20160210_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='_public_id',
            field=models.CharField(blank=True, db_column='public_id', db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='_secret_id',
            field=models.CharField(blank=True, db_column='secret_id', db_index=True, max_length=64, null=True),
        ),
    ]
