# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0003_auto_20160210_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
