# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('kdata', '0007_auto_20160307_0105'), ('kdata', '0008_auto_20160307_0121'), ('kdata', '0009_surveytoken_persistent'), ('kdata', '0010_auto_20160308_2352'), ('kdata', '0011_auto_20160309_1223')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kdata', '0006_auto_20160303_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kdata.Device')),
                ('token', models.CharField(blank=True, help_text='The survey token, or blank for ephemeral surveys', max_length=32, null=True)),
                ('persistent', models.BooleanField(default=True, help_text='Does this survey have different tokens for each taking?')),
                ('pyclass', models.CharField(blank=True, max_length=128)),
                ('pyclass_data', models.CharField(blank=True, max_length=256)),
                ('send_via', models.CharField(blank=True, help_text='How to send survey to person?', max_length=128)),
                ('survey_active', models.BooleanField(default=True, help_text='Will this survey send notifications?')),
            ],
            bases=('kdata.device',),
        ),
        migrations.CreateModel(
            name='SurveyToken',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_access', models.DateTimeField(blank=True, null=True)),
                ('ts_submit', models.DateTimeField(blank=True, null=True)),
                ('ts_expire', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('data', models.CharField(blank=True, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persistent', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Android', 'Android'), ('PurpleRobot', 'Purple Robot (Android)'), ('Ios', 'IOS'), ('MurataBSN', 'Murata Bed Sensor'), ('kdata.survey.TestSurvey1', 'Test Survey #1')], help_text='What type of device is this?', max_length=128),
        ),
    ]
