# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kdata', '0006_auto_20160303_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='kdata.Device')),
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('persistent', models.BooleanField(default=True)),
                ('pyclass', models.CharField(max_length=128)),
                ('pyclass_data', models.CharField(max_length=256)),
            ],
            bases=('kdata.device',),
        ),
        migrations.CreateModel(
            name='SurveyToken',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_access', models.DateTimeField(blank=True, null=True)),
                ('ts_submit', models.DateTimeField(blank=True, null=True)),
                ('ts_expire', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('data', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Android', 'Android'), ('PurpleRobot', 'Purple Robot (Android)'), ('Ios', 'IOS'), ('MurataBSN', 'Murata Bed Sensor'), ('kdata.survey.TestSurvey1', 'Test Survey #1')], help_text='What type of device is this?', max_length=128),
        ),
    ]
