# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0007_auto_20160307_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydevice',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kdata.Device'),
        ),
        migrations.AlterField(
            model_name='surveydevice',
            name='token',
            field=models.CharField(max_length=32),
        ),
    ]
