# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0008_add_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kdata.Device')),
                ('service', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=16)),
                ('error', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=265)),
                ('request_key', models.CharField(max_length=256)),
                ('request_secret', models.CharField(max_length=256)),
                ('resource_key', models.CharField(max_length=256)),
                ('resource_secret', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_linked', models.BooleanField(default=False)),
                ('ts_last_fetch', models.DateTimeField(blank=True, null=True)),
                ('ts_refresh', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('kdata.device',),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Android', 'Android'), ('PurpleRobot', 'Purple Robot (Android)'), ('Ios', 'IOS'), ('MurataBSN', 'Murata Bed Sensor'), ('kdata.devices.Actiwatch', 'Philips Actiwatch'), ('kdata.views_funf.FunfJournal', 'Funf-journal device'), ('kdata.survey.TestSurvey1', 'Test Survey #1'), ('kdata.twitter.Twitter', 'Twitter')], help_text='What type of device is this?', max_length=128),
        ),
    ]
