# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0009_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelabel',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='nonanonymous',
            field=models.BooleanField(default=False),
        ),
    ]
