# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0010_auto_20160308_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydevice',
            name='send_via',
            field=models.CharField(blank=True, help_text='How to send survey to person?', max_length=128),
        ),
        migrations.AddField(
            model_name='surveydevice',
            name='survey_active',
            field=models.BooleanField(default=True, help_text='Will this survey send notifications?'),
        ),
        migrations.AlterField(
            model_name='surveydevice',
            name='persistent',
            field=models.BooleanField(default=True, help_text='Does this survey have different tokens for each taking?'),
        ),
        migrations.AlterField(
            model_name='surveydevice',
            name='pyclass',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='surveydevice',
            name='pyclass_data',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='surveydevice',
            name='token',
            field=models.CharField(blank=True, help_text='The survey token, or blank for ephemeral surveys', max_length=32, null=True),
        ),
    ]
