# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0010_group_and_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ts_received',
            field=models.DateTimeField(auto_now_add=True, help_text='Time packet received (never updated)', null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the data referrs to, defaults to received timestamp.'),
        ),
    ]
