# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import kdata.util


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0011_data_ts_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='salt',
            field=models.CharField(default=kdata.util.random_salt_b64, max_length=128),
        ),
        migrations.AddField(
            model_name='groupresearcher',
            name='manager',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('kdata.devices.Ios', 'iOS (our app)'), ('Ios', 'iOS (our app)'), ('kdata.devices.Android', 'Android'), ('Android', 'Android'), ('kdata.devices.PurpleRobot', 'PurpleRobot'), ('PurpleRobot', 'PurpleRobot'), ('kdata.devices.MurataBSN', 'MurataBSN'), ('MurataBSN', 'MurataBSN'), ('kdata.devices.Actiwatch', 'Philips Actiwatch'), ('kdata.devices.Actiwatch', 'Philips Actiwatch'), ('kdata.funf.FunfJournal', 'Funf-journal device'), ('kdata.funf.FunfJournal', 'Funf-journal device'), ('kdata.survey.TestSurvey1', 'Test Survey #1'), ('kdata.twitter.Twitter', 'Twitter'), ('kdata.twitter.Twitter', 'Twitter')], help_text='What type of device is this?', max_length=128),
        ),
    ]
