# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kdata.util


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0012_group_salt_grmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='salt',
            field=models.CharField(blank=True, default=kdata.util.random_salt_b64, max_length=128),
        ),
    ]
