# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0013_group_salt_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute name', max_length=64)),
                ('value', models.CharField(help_text='Attribute value', max_length=128)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='deviceattr',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdata.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceattr',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='deviceattr',
            index_together=set([('name', 'value'), ('device', 'name')]),
        ),
    ]
