# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import kdata.util


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0015_mosquittoauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='config',
            field=kdata.util.JsonConfigField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='priority',
            field=models.IntegerField(default=10, help_text='In what order should group configuration be applied?  higher=more priority'),
        ),
    ]
