# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0017_auto_20160809_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelabel',
            name='analyze',
            field=models.BooleanField(default=False, help_text='Include this label in analysis?'),
        ),
        migrations.AddField(
            model_name='devicelabel',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in UI.'),
        ),
        migrations.AddField(
            model_name='devicelabel',
            name='shortname',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='group',
            name='desc_long',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='url_privacy',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='devicelabel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicelabel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicelabel',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='slug for querying', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='pyclass',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='pyclass_data',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
