# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0018_devicelabel_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute name', max_length=64)),
                ('value', models.CharField(help_text='Attribute value', max_length=128)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdata.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupattr',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='groupattr',
            index_together=set([('device', 'name'), ('name', 'value')]),
        ),
    ]
