# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import kdata.util


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0019_groupattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived',
            field=models.BooleanField(default=False, help_text='Is this study archived?'),
        ),
        migrations.AddField(
            model_name='group',
            name='leaveable',
            field=models.BooleanField(default=False, help_text='Can subjects can leave this study by themselves?'),
        ),
        migrations.AddField(
            model_name='groupresearcher',
            name='admin',
            field=models.NullBooleanField(default=False, help_text='Has access to adjust group properties?'),
        ),
        migrations.AddField(
            model_name='groupresearcher',
            name='researcher',
            field=models.NullBooleanField(default=None, help_text='Has access to data?'),
        ),
        migrations.AddField(
            model_name='groupsubject',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this study available for joining and active?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='config',
            field=kdata.util.JsonConfigField(blank=True, help_text='Arbitrary JSON configuration for this group.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.CharField(help_text='Short description (64 chars)', max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc_long',
            field=models.TextField(blank=True, help_text='Long description explaining study.  Include contact info.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Invite code, for subjects to join.', max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='managed',
            field=models.BooleanField(default=False, help_text='If true, managers will be able to control devices.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Name of study, for humans.', max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='nonanonymous',
            field=models.BooleanField(default=False, help_text='If true, usernames and device IDs, and individual device data will be visible to researchers'),
        ),
        migrations.AlterField(
            model_name='group',
            name='otp_required',
            field=models.BooleanField(default=False, help_text='Require 2FA for researchers?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='priority',
            field=models.IntegerField(default=0, help_text='In what order should group configuration be applied?  higher=more priority'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pyclass',
            field=models.CharField(blank=True, help_text='Python class which manages this object.', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='pyclass_data',
            field=models.CharField(blank=True, help_text='Configuration data for Python class.', max_length=256),
        ),
        migrations.AlterField(
            model_name='group',
            name='salt',
            field=models.CharField(blank=True, default=kdata.util.random_salt_b64, help_text='A hash salt for this group', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(help_text='Short unique identifier, no spaces.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ts_end',
            field=models.DateTimeField(blank=True, help_text='Timestamp end, data available before this time.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ts_start',
            field=models.DateTimeField(blank=True, help_text='Timestamp start, data available after this time.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.CharField(blank=True, help_text='URL with more study information.', max_length=256),
        ),
        migrations.AlterField(
            model_name='group',
            name='url_privacy',
            field=models.CharField(blank=True, help_text='URL with study privacy information.', max_length=256),
        ),
        migrations.AlterField(
            model_name='groupresearcher',
            name='manager',
            field=models.NullBooleanField(default=False, help_text='Has access to manage users?'),
        ),
    ]
