# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0020_group_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='archived',
            field=models.BooleanField(default=False, help_text="Is this device no longer in use?  This hides this device from some views but doesn't change anything else."),
        ),
    ]
