# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0021_device_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthdevice',
            name='ts_create',
        ),
        migrations.AddField(
            model_name='device',
            name='ts_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ts_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
