# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0022_device_ts_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='locked',
            field=models.BooleanField(default=False, help_text='If locked, subjects can not adjust parameters themselves.'),
        ),
    ]
