# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0023_locked_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceattr',
            name='value',
            field=models.CharField(help_text='Attribute value', max_length=4096),
        ),
        migrations.AlterField(
            model_name='groupattr',
            name='value',
            field=models.CharField(help_text='Attribute value', max_length=4096),
        ),
    ]
