# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kdata', '0025_consents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_expire', models.DateTimeField(db_index=True)),
                ('delete_permanently', models.BooleanField(default=False)),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
