# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0026_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privacy_stmt',
            field=models.TextField(blank=True, help_text='Text of the study privacy information.'),
        ),
    ]
