# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0027_group_privacy_stmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='n_packets_cache',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='n_packets_cache_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
