# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0028_n_packets_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubjectAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute name', max_length=64)),
                ('value', models.CharField(help_text='Attribute value', max_length=4096)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdata.GroupSubject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupsubjectattr',
            unique_together=set([('device', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='groupsubjectattr',
            index_together=set([('device', 'name'), ('name', 'value')]),
        ),
    ]
