# Generated by Django 2.1.1 on 2018-11-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0030_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='n_packets_cache',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
