# Generated by Django 2.1.1 on 2020-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdata', '0031_device_blank_ncache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceattr',
            name='value',
            field=models.CharField(help_text='Attribute value', max_length=16384),
        ),
        migrations.AlterField(
            model_name='groupattr',
            name='value',
            field=models.CharField(help_text='Attribute value', max_length=16384),
        ),
        migrations.AlterField(
            model_name='groupsubjectattr',
            name='value',
            field=models.CharField(help_text='Attribute value', max_length=16384),
        ),
    ]
